-- local config = {
--     cmd = {'/home/blipin/.local/share/nvim/mason/bin/jdtls --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml'},
--     root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
-- }
-- require('jdtls').start_or_attach(config)
